### ISSUE TITLE
Line 51 of ConnectionExtensions.cs

### ISSUE THREAD

**Issue by NVentimiglia** [oising/Nivot.SignalR.Client.Net35#1]
jsonWriter.Formatting = connection.JsonSerializer.Formatting;

What does this do? Is it necessary?

 I ask because I am using this solution with an older variant of Json.net which does not have this Formatting property.

**Comment by oising** [comment]
I don't know - I am not the author of that part of the client. I only did the bare minimum to back port it to net35.
