### ISSUE TITLE
Is this compatible with .Net3.5 CE?

### ISSUE THREAD

**Issue by shadabmustaafa** [oising/Nivot.SignalR.Client.Net35#5]
I need to use SignalR with a WinCE device which is on WEC7 running compact .Net3.5 version.

**Comment by oising** [comment]
I have absolutely no idea. Go find out :)

**Comment by queBurro** [comment]
@shadabmustaafa did you have any luck getting this working on WinCE? Cheers

**Comment by shadabmustaafa** [comment]
No, this doesn't work on .net 3.5 CE

**Comment by shadabmustaafa** [comment]
No, that’s not compatible with CE. In fact I couldn’t find any reasonable client for SignalR on CF3.5. If you find one, let me know as well.

Regards,
Syed Shadab Mustafa | Team Lead Software Engineer
Mob: +974 6621 4396
Email: smustafa@karwasolutions.com<mailto:smustafa@karwasolutions.com> | Web: http://www.karwasolutions.com

**Comment by queBurro** [comment]
Sure, I'll let you know if I find anything. I've had a quick look at retargetting this to .Net CF 3.5 and compiling with VS2008 but I'm hitting issues with the later VS supporting newer keywords.

**Comment by shadabmustaafa** [comment]
Apart from that, this library heavily depends on TPL library provided by .net 3.5 onwards, which is not part of .net 3.5CF.

Regards,
Syed Shadab Mustafa | Team Lead Software Engineer
Mob: +974 6621 4396
Email: smustafa@karwasolutions.com<mailto:smustafa@karwasolutions.com> | Web: http://www.karwasolutions.com

**Comment by queBurro** [comment]
Ah ok, thanks for letting me know.

**Comment by oising** [comment]
No, not compatible with CE 3.5
